apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: 211125415675.dkr.ecr.ap-south-1.amazonaws.com/webapp1:latest
        ports:
        - containerPort: 80
